export const themes = [
  "A vida secreta de uma colher na gaveta",
  "Como seria o mundo governado por gatos",
  "Manual de sobrevivência em uma ilha feita de gelatina",
  "O dia em que acordei com superpoderes inúteis",
  "Entrevista de emprego para ser um unicórnio",
  "Receita de bolo que dá errado de propósito",
  "Diário de uma meia perdida na lavanderia",
  "Como explicar o Wi-Fi para um dinossauro",
  "O dilema de um vampiro vegano",
  "Um tutorial sobre como conquistar um ET",
  "O que os patos realmente conversam quando ninguém está olhando",
  "Minha vida como um emoji de WhatsApp",
  "Conselhos amorosos de um peixe dourado",
  "O mistério da pizza que nunca acaba",
  "A jornada épica de uma barata que queria ser astronauta",
  "Como criar uma sociedade secreta com formigas do quintal",
  "O guia definitivo para irritar um robô",
  "O sonho estranho que tive depois de comer sushi de madrugada",
  "Como seria uma olimpíada só com idosos de 100 anos",
  "A guerra silenciosa entre as almofadas do sofá",
];
